### ISSUE TITLE
Partial Dark Mode

### ISSUE THREAD

**Issue by talon2g** [m4heshd/whatsapp-desktop-dark#113]
Was working fine until today.. chat bar and status bar are now white. Tried restarting computer, deleting/reinstalling into whatsapp directory, etc.
![WhatsApp_LVLJUk4qBg](https://user-images.githubusercontent.com/60020006/72650541-d6ab3c00-394e-11ea-9d95-50b43731d61b.png)

**Comment by purplpasta** [comment]
Yeah I have the same problem, this is especially annoying since whatsapp updates itself automatically, and I don't think you can disable auto update, can you?

**Comment by talon2g** [comment]
> Yeah I have the same problem, this is especially annoying since whatsapp updates itself automatically, and I don't think you can disable auto update, can you?

I don't believe you can disable auto updates, no.

**Comment by fistachio-2k** [comment]
As well guys... Im using MacOS, is it an issue of OS type?

**Comment by radu-nh** [comment]
Got the same issue, I guess it just doesn't work with the latest version (0.4.315)

**Comment by jobw** [comment]
yup, same here

**Comment by MarioFlying** [comment]
Same.

**Comment by melonpng** [comment]
same here.

**Comment by wazowski78** [comment]
WhatsApp has made some changes in the app, so I suppose the same have to be done here.

**Comment by uropek-cyber** [comment]
same

**Comment by MarioFlying** [comment]
Hello, I'm sure that m4heshd will provide a fix soon enough but in the meanwhile I'm able to run the dark mode as intended by simply executing
`C:\Users\MY_USERNAME\AppData\Local\WhatsApp\app-0.3.9309\Whatsapp.exe`
instead of
`C:\Users\MY_USERNAME\AppData\Local\WhatsApp\Whatsapp.exe`.

It seems to work just fine and it can't update over itself, since the update is already installed in the `app-0.4.315` folder -- which I'm just leaving there. I've 7zipped the old folder, just in case.

I hope it works for you guys as well. Bye

**Comment by 3B4252** [comment]
> 
> 
> Hello, I'm sure that m4heshd will provide a fix soon enough but in the meanwhile I'm able to run the dark mode as intended by simply executing
> `C:\Users\MY_USERNAME\AppData\Local\WhatsApp\app-0.3.9309\Whatsapp.exe`
> instead of
> `C:\Users\MY_USERNAME\AppData\Local\WhatsApp\Whatsapp.exe`.
> 
> It seems to work just fine and it can't update over itself, since the update is already installed in the `app-0.4.315` folder -- which I'm just leaving there. I've 7zipped the old folder, just in case.
> 
> I hope it works for you guys as well. Bye

I tried, but whatsapp opens with the default theme :/

**Comment by MarioFlying** [comment]
> I tried, but whatsapp opens with the default theme :/

Try to re-apply the theme executing `wadark.exe` after opening
`C:\Users\MY_USERNAME\AppData\Local\WhatsApp\app-0.3.9309\Whatsapp.exe` and see if it works

**Comment by 3B4252** [comment]
> 
> 
> > I tried, but whatsapp opens with the default theme :/
> 
> Try to re-apply the theme executing `wadark.exe` after opening
> `C:\Users\MY_USERNAME\AppData\Local\WhatsApp\app-0.3.9309\Whatsapp.exe` and see if it works

Now I have only the left part white, but yeah... I'm waiting for the new update :D

**Comment by m4heshd** [comment]
Everyone, please refer https://github.com/m4heshd/whatsapp-desktop-dark/pull/85#issuecomment-580186382.

**Comment by m4heshd** [comment]
Closing this since the issue has been fixed in the latest release.

**Comment by kriznik** [comment]
Hi,
I have this issue with latest release, from today. Till today everything worked just fine. Tried several times, still the same result as OP.
